defmodule EmisintWeb.ErrorFileDownloadController do
  use EmisintWeb, :controller

  require Logger

  @doc """
  Downloads an import error CSV file generated by one of the MDE importers.

  Security:
    - Requires an authenticated system_admin user (enforced via the plug pipeline
      and an explicit role check here).
    - Validates that the requested path lives inside the OS temp directory and
      ends with `_errors.csv` so only files written by the importers can be served
      (prevents path traversal to arbitrary server files).
  """
  def download(conn, %{"path" => file_path}) do
    with :ok <- check_admin(conn),
         :ok <- validate_path(file_path),
         true <- File.exists?(file_path) do
      filename = Path.basename(file_path)

      conn
      |> put_resp_content_type("text/csv")
      |> put_resp_header("content-disposition", ~s(attachment; filename="#{filename}"))
      |> send_file(200, file_path)
    else
      {:error, :not_admin} ->
        conn
        |> put_status(:forbidden)
        |> text("Forbidden")

      {:error, :invalid_path} ->
        conn
        |> put_status(:bad_request)
        |> text("Invalid file path")

      false ->
        conn
        |> put_status(:not_found)
        |> text("Error file not found — it may have already been cleaned up")
    end
  rescue
    e ->
      Logger.error("[ErrorFileDownloadController] #{Exception.message(e)}")

      conn
      |> put_status(:internal_server_error)
      |> text("Download failed")
  end

  # ---------------------------------------------------------------------------
  # Guards
  # ---------------------------------------------------------------------------

  defp check_admin(conn) do
    case conn.assigns[:current_user] do
      %{role: :system_admin} -> :ok
      _ -> {:error, :not_admin}
    end
  end

  # Accepts only paths that:
  #   1. Reside inside the OS temp directory (no escaping via "..")
  #   2. End with "_errors.csv" (only files written by the importers)
  defp validate_path(path) do
    tmp = System.tmp_dir!()
    expanded = Path.expand(path)

    if String.starts_with?(expanded, tmp) and String.ends_with?(expanded, "_errors.csv") do
      :ok
    else
      {:error, :invalid_path}
    end
  end
end
