defmodule Emisint.Repo.Migrations.AddAssessmentsDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:competitor_data, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :district_name, :text, null: false
      add :mde_district_code, :text, null: false
      add :subject, :text, null: false
      add :grade_level, :text, null: false
      add :proficiency_rate, :decimal, null: false
      add :average_sgp, :decimal
      add :student_count, :bigint
      add :academic_year_label, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(
             :competitor_data,
             [:mde_district_code, :subject, :grade_level, :academic_year_label],
             name: "competitor_data_unique_district_subject_grade_year_index"
           )

    create table(:benchmark_providers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :code, :text, null: false
      add :scoring_system, :text, null: false
      add :subjects, {:array, :text}, null: false, default: []
      add :organization_id, :uuid, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:benchmark_providers, [:organization_id, :code],
             name: "benchmark_providers_unique_code_per_org_index"
           )

    create table(:assessment_results, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :assessment_type, :text, null: false
      add :subject, :text, null: false
      add :testing_window, :text, null: false
      add :raw_score, :decimal
      add :scale_score, :decimal
      add :proficiency_level, :text
      add :sgp, :bigint
      add :growth_target, :decimal
      add :percentile, :bigint
      add :test_date, :date
      add :source, :text
      add :organization_id, :uuid, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :student_id,
          references(:students,
            column: :id,
            name: "assessment_results_student_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :academic_year_id,
          references(:academic_years,
            column: :id,
            name: "assessment_results_academic_year_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(
             :assessment_results,
             [
               :organization_id,
               :student_id,
               :academic_year_id,
               :assessment_type,
               :subject,
               :testing_window
             ],
             name: "assessment_results_unique_assessment_per_window_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :assessment_results,
                     [
                       :organization_id,
                       :student_id,
                       :academic_year_id,
                       :assessment_type,
                       :subject,
                       :testing_window
                     ],
                     name: "assessment_results_unique_assessment_per_window_index"
                   )

    drop constraint(:assessment_results, "assessment_results_student_id_fkey")

    drop constraint(:assessment_results, "assessment_results_academic_year_id_fkey")

    drop table(:assessment_results)

    drop_if_exists unique_index(:benchmark_providers, [:organization_id, :code],
                     name: "benchmark_providers_unique_code_per_org_index"
                   )

    drop table(:benchmark_providers)

    drop_if_exists unique_index(
                     :competitor_data,
                     [:mde_district_code, :subject, :grade_level, :academic_year_label],
                     name: "competitor_data_unique_district_subject_grade_year_index"
                   )

    drop table(:competitor_data)
  end
end
