defmodule Emisint.Repo.Migrations.MdePublicData do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mde_state_assessment_results, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :school_year, :text, null: false
      add :test_type, :text, null: false
      add :test_population, :text, null: false
      add :grade_content_tested, :text, null: false
      add :subject, :text, null: false
      add :report_category, :text, null: false
      add :total_advanced, :bigint
      add :total_proficient, :bigint
      add :total_partially_proficient, :bigint
      add :total_not_proficient, :bigint
      add :total_surpassed, :bigint
      add :total_attained, :bigint
      add :total_emerging_towards, :bigint
      add :total_met, :bigint
      add :total_did_not_meet, :bigint
      add :number_assessed, :bigint
      add :percent_advanced, :decimal
      add :percent_proficient, :decimal
      add :percent_partially_proficient, :decimal
      add :percent_not_proficient, :decimal
      add :percent_surpassed, :decimal
      add :percent_attained, :decimal
      add :percent_emerging_towards, :decimal
      add :percent_met, :decimal
      add :percent_did_not_meet, :decimal
      add :avg_ss, :decimal
      add :std_dev_ss, :decimal
      add :mean_pts_earned, :decimal
      add :min_scale_score, :decimal
      add :max_scale_score, :decimal
      add :scale_score_25, :decimal
      add :scale_score_50, :decimal
      add :scale_score_75, :decimal

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :mde_building_id, :uuid, null: false
    end

    create table(:mde_isds, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :isd_code, :text, null: false
      add :isd_name, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:mde_isds, [:isd_code], name: "mde_isds_unique_isd_code_index")

    create table(:mde_districts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :district_code, :text, null: false
      add :district_name, :text, null: false
      add :county_code, :text
      add :county_name, :text
      add :entity_type, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :mde_isd_id,
          references(:mde_isds,
            column: :id,
            name: "mde_districts_mde_isd_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:mde_districts, [:district_code],
             name: "mde_districts_unique_district_code_index"
           )

    create table(:mde_buildings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:mde_state_assessment_results) do
      modify :mde_building_id,
             references(:mde_buildings,
               column: :id,
               name: "mde_state_assessment_results_mde_building_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(
             :mde_state_assessment_results,
             [
               :mde_building_id,
               :school_year,
               :test_type,
               :test_population,
               :grade_content_tested,
               :subject,
               :report_category
             ],
             name: "mde_state_assessment_results_unique_result_index"
           )

    alter table(:mde_buildings) do
      add :building_code, :text, null: false
      add :building_name, :text, null: false
      add :school_level, :text
      add :locale, :text
      add :mistem_name, :text
      add :mistem_code, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :mde_district_id,
          references(:mde_districts,
            column: :id,
            name: "mde_buildings_mde_district_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:mde_buildings, [:building_code],
             name: "mde_buildings_unique_building_code_index"
           )
  end

  def down do
    drop_if_exists unique_index(:mde_buildings, [:building_code],
                     name: "mde_buildings_unique_building_code_index"
                   )

    drop constraint(:mde_buildings, "mde_buildings_mde_district_id_fkey")

    alter table(:mde_buildings) do
      remove :mde_district_id
      remove :updated_at
      remove :created_at
      remove :mistem_code
      remove :mistem_name
      remove :locale
      remove :school_level
      remove :building_name
      remove :building_code
    end

    drop_if_exists unique_index(
                     :mde_state_assessment_results,
                     [
                       :mde_building_id,
                       :school_year,
                       :test_type,
                       :test_population,
                       :grade_content_tested,
                       :subject,
                       :report_category
                     ],
                     name: "mde_state_assessment_results_unique_result_index"
                   )

    drop constraint(
           :mde_state_assessment_results,
           "mde_state_assessment_results_mde_building_id_fkey"
         )

    alter table(:mde_state_assessment_results) do
      modify :mde_building_id, :uuid
    end

    drop table(:mde_buildings)

    drop_if_exists unique_index(:mde_districts, [:district_code],
                     name: "mde_districts_unique_district_code_index"
                   )

    drop constraint(:mde_districts, "mde_districts_mde_isd_id_fkey")

    drop table(:mde_districts)

    drop_if_exists unique_index(:mde_isds, [:isd_code], name: "mde_isds_unique_isd_code_index")

    drop table(:mde_isds)

    drop table(:mde_state_assessment_results)
  end
end
