defmodule Emisint.Repo.Migrations.AddMdeComparisonSnapshots do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mde_school_vs_lea_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :building_code, :text, null: false
      add :school_year, :text, null: false
      add :school_name, :text
      add :lea_district_code, :text
      add :lea_district_name, :text
      add :above_lea, :bigint, default: 0
      add :below_lea, :bigint, default: 0
      add :above_state, :bigint, default: 0
      add :grades_compared, :bigint, default: 0
      add :no_lea_found, :boolean, default: false
      add :no_results, :boolean, default: false
      add :no_lea_results, :boolean, default: false
      add :no_state_results, :boolean, default: false
      add :subject_comparison, {:array, :map}
      add :all_subjects_avg, :map
      add :grade_breakdown, {:array, :map}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:mde_school_vs_lea_snapshots, [:building_code, :school_year])

    create index(:mde_school_vs_lea_snapshots, [:school_year])

    create unique_index(:mde_school_vs_lea_snapshots, [:building_code, :school_year],
             name: "mde_school_vs_lea_snapshots_unique_building_year_index"
           )

    create table(:mde_district_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :district_code, :text, null: false
      add :school_year, :text, null: false
      add :district_name, :text
      add :entity_type, :text
      add :isd_name, :text
      add :buildings, :bigint, default: 0
      add :total_assessed, :bigint, default: 0
      add :ela_pct, :float
      add :math_pct, :float
      add :avg_total_proficient, :float
      add :all_subjects, :map
      add :grade_breakdown, {:array, :map}
      add :proficiency_dist, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:mde_district_snapshots, [:district_code, :school_year])

    create index(:mde_district_snapshots, [:school_year])

    create unique_index(:mde_district_snapshots, [:district_code, :school_year],
             name: "mde_district_snapshots_unique_district_year_index"
           )
  end

  def down do
    drop_if_exists unique_index(:mde_district_snapshots, [:district_code, :school_year],
                     name: "mde_district_snapshots_unique_district_year_index"
                   )

    drop_if_exists index(:mde_district_snapshots, [:school_year])

    drop_if_exists index(:mde_district_snapshots, [:district_code, :school_year])

    drop table(:mde_district_snapshots)

    drop_if_exists unique_index(:mde_school_vs_lea_snapshots, [:building_code, :school_year],
                     name: "mde_school_vs_lea_snapshots_unique_building_year_index"
                   )

    drop_if_exists index(:mde_school_vs_lea_snapshots, [:school_year])

    drop_if_exists index(:mde_school_vs_lea_snapshots, [:building_code, :school_year])

    drop table(:mde_school_vs_lea_snapshots)
  end
end
