defmodule Emisint.Repo.Migrations.AddComplianceDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:schedule71_goals_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :organization_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:schedule71_goals, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:schedule71_goals_versions) do
      modify :version_source_id,
             references(:schedule71_goals,
               column: :id,
               name: "schedule71_goals_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:schedule71_goals) do
      add :title, :text, null: false
      add :goal_type, :text, null: false
      add :subject, :text, null: false
      add :grade_levels, {:array, :text}, null: false, default: []
      add :testing_window, :text, null: false
      add :assessment_type, :text
      add :target_value, :decimal, null: false
      add :comparison_operator, :text, null: false, default: "gte"
      add :exceeds_threshold, :decimal
      add :approaching_threshold, :decimal
      add :subgroup, :text
      add :organization_id, :uuid, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :school_id,
          references(:schools,
            column: :id,
            name: "schedule71_goals_school_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :charter_contract_id, :uuid
    end

    create table(:goal_evaluations_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :organization_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:goal_evaluations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:goal_evaluations_versions) do
      modify :version_source_id,
             references(:goal_evaluations,
               column: :id,
               name: "goal_evaluations_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:goal_evaluations) do
      add :status, :text, null: false, default: "insufficient_data"
      add :actual_value, :decimal
      add :target_value, :decimal
      add :comparison_operator, :text
      add :exceeds_threshold, :decimal
      add :approaching_threshold, :decimal
      add :data_points_count, :bigint, null: false, default: 0

      add :evaluated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id, :uuid, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :schedule71_goal_id,
          references(:schedule71_goals,
            column: :id,
            name: "goal_evaluations_schedule71_goal_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :academic_year_id,
          references(:academic_years,
            column: :id,
            name: "goal_evaluations_academic_year_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(
             :goal_evaluations,
             [:organization_id, :schedule71_goal_id, :academic_year_id],
             name: "goal_evaluations_unique_goal_year_evaluation_index"
           )

    create table(:charter_contracts_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :organization_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:charter_contracts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:schedule71_goals) do
      modify :charter_contract_id,
             references(:charter_contracts,
               column: :id,
               name: "schedule71_goals_charter_contract_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:charter_contracts_versions) do
      modify :version_source_id,
             references(:charter_contracts,
               column: :id,
               name: "charter_contracts_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:charter_contracts) do
      add :authorizer_name, :text, null: false
      add :contract_start_date, :date, null: false
      add :contract_end_date, :date, null: false
      add :reauthorization_date, :date
      add :status, :text, null: false, default: "active"
      add :organization_id, :uuid, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :school_id,
          references(:schools,
            column: :id,
            name: "charter_contracts_school_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:charter_contracts, "charter_contracts_school_id_fkey")

    alter table(:charter_contracts) do
      remove :school_id
      remove :updated_at
      remove :created_at
      remove :organization_id
      remove :status
      remove :reauthorization_date
      remove :contract_end_date
      remove :contract_start_date
      remove :authorizer_name
    end

    drop constraint(
           :charter_contracts_versions,
           "charter_contracts_versions_version_source_id_fkey"
         )

    alter table(:charter_contracts_versions) do
      modify :version_source_id, :uuid
    end

    drop constraint(:schedule71_goals, "schedule71_goals_charter_contract_id_fkey")

    alter table(:schedule71_goals) do
      modify :charter_contract_id, :uuid
    end

    drop table(:charter_contracts)

    drop table(:charter_contracts_versions)

    drop_if_exists unique_index(
                     :goal_evaluations,
                     [:organization_id, :schedule71_goal_id, :academic_year_id],
                     name: "goal_evaluations_unique_goal_year_evaluation_index"
                   )

    drop constraint(:goal_evaluations, "goal_evaluations_schedule71_goal_id_fkey")

    drop constraint(:goal_evaluations, "goal_evaluations_academic_year_id_fkey")

    alter table(:goal_evaluations) do
      remove :academic_year_id
      remove :schedule71_goal_id
      remove :updated_at
      remove :created_at
      remove :organization_id
      remove :evaluated_at
      remove :data_points_count
      remove :approaching_threshold
      remove :exceeds_threshold
      remove :comparison_operator
      remove :target_value
      remove :actual_value
      remove :status
    end

    drop constraint(
           :goal_evaluations_versions,
           "goal_evaluations_versions_version_source_id_fkey"
         )

    alter table(:goal_evaluations_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:goal_evaluations)

    drop table(:goal_evaluations_versions)

    drop constraint(:schedule71_goals, "schedule71_goals_school_id_fkey")

    alter table(:schedule71_goals) do
      remove :charter_contract_id
      remove :school_id
      remove :updated_at
      remove :created_at
      remove :organization_id
      remove :subgroup
      remove :approaching_threshold
      remove :exceeds_threshold
      remove :comparison_operator
      remove :target_value
      remove :assessment_type
      remove :testing_window
      remove :grade_levels
      remove :subject
      remove :goal_type
      remove :title
    end

    drop constraint(
           :schedule71_goals_versions,
           "schedule71_goals_versions_version_source_id_fkey"
         )

    alter table(:schedule71_goals_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:schedule71_goals)

    drop table(:schedule71_goals_versions)
  end
end
