defmodule Emisint.Repo.Migrations.AddOrgMdeDistrictCode do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organizations) do
      add :mde_district_code, :text
    end
  end

  def down do
    alter table(:organizations) do
      remove :mde_district_code
    end
  end
end
