defmodule Emisint.Repo.Migrations.AddPercentMetApproximate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:mde_state_assessment_results) do
      add :percent_met_approximate, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:mde_state_assessment_results) do
      remove :percent_met_approximate
    end
  end
end
