defmodule Emisint.Repo.Migrations.EntityMaster do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mde_entity_masters, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :entity_code, :text, null: false
      add :isd_code, :text
      add :isd_official_name, :text
      add :district_code, :text
      add :district_official_name, :text
      add :district_type, :text
      add :district_type_name, :text
      add :district_common_name, :text
      add :entity_official_name, :text
      add :agreement_number, :text
      add :entity_type, :text
      add :entity_type_name, :text
      add :entity_type_group, :text
      add :entity_type_group_name, :text
      add :entity_type_category, :text
      add :entity_type_category_name, :text
      add :entity_county_code, :text
      add :entity_county_name, :text
      add :entity_chartering_agency_code, :text
      add :entity_chartering_agency_name, :text
      add :entity_geographic_lea_district_code, :text
      add :entity_geographic_lea_district_official_name, :text
      add :entity_nces_code, :text
      add :entity_locale_code, :text
      add :entity_locale_name, :text
      add :entity_fips_code, :text
      add :entity_remc_id, :text
      add :entity_authorized_educational_settings, :text
      add :entity_actual_educational_settings, :text
      add :entity_authorized_grades, :text
      add :entity_actual_grades, :text
      add :entity_status, :text
      add :entity_open_date, :text
      add :entity_close_date, :text
      add :entity_schedules_list, :text
      add :entity_early_childhood_program_list, :text
      add :receives_transportation_from_code, :text
      add :receives_transportation_from_name, :text
      add :entity_religious_orientation_code, :text
      add :entity_religious_orientation_name, :text
      add :entity_email, :text
      add :entity_phone, :text
      add :entity_phone_ext, :text
      add :entity_fax, :text
      add :entity_fax_ext, :text
      add :entity_lead_admin_honorific, :text
      add :entity_lead_admin_first_name, :text
      add :entity_lead_admin_last_name, :text
      add :entity_physical_street, :text
      add :entity_physical_city, :text
      add :entity_physical_state, :text
      add :entity_physical_zip4, :text
      add :entity_mailing_street, :text
      add :entity_mailing_city, :text
      add :entity_mailing_state, :text
      add :entity_mailing_zip4, :text
      add :early_middle_college, :text
      add :see_type, :text
      add :head_start_grantee, :text
      add :school_emphasis, :text
      add :essa_support_category_status, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:mde_entity_masters, [:entity_code],
             name: "mde_entity_masters_unique_entity_code_index"
           )
  end

  def down do
    drop_if_exists unique_index(:mde_entity_masters, [:entity_code],
                     name: "mde_entity_masters_unique_entity_code_index"
                   )

    drop table(:mde_entity_masters)
  end
end
