defmodule Emisint.Repo.Migrations.AddDistrictNameTrgmIndexExtensions1 do
  @moduledoc """
  Installs any extensions that are mentioned in the repo's `installed_extensions/0` callback

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE EXTENSION IF NOT EXISTS \"pg_trgm\"")

    execute("""
    CREATE INDEX IF NOT EXISTS mde_district_snapshots_district_name_gin_trgm_idx
    ON mde_district_snapshots
    USING gin (district_name gin_trgm_ops)
    """)
  end

  def down do
    execute("DROP INDEX IF EXISTS mde_district_snapshots_district_name_gin_trgm_idx")
    # execute("DROP EXTENSION IF EXISTS \"pg_trgm\"")
  end
end
