defmodule Emisint.Repo.Migrations.AddMdeIndexThreshold do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mde_index_thresholds, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :school_year, :text, null: false
      add :component, :text, null: false
      add :threshold_value, :decimal, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:mde_index_thresholds, [:school_year, :component],
             name: "mde_index_thresholds_unique_component_year_index"
           )
  end

  def down do
    drop_if_exists unique_index(:mde_index_thresholds, [:school_year, :component],
                     name: "mde_index_thresholds_unique_component_year_index"
                   )

    drop table(:mde_index_thresholds)
  end
end
