defmodule Emisint.Repo.Migrations.AddOrgContactAndCharteringAgency do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:schools) do
      add :chartering_agency_id,
          references(:organizations,
            column: :id,
            name: "schools_chartering_agency_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:organizations) do
      add :primary_contact_name, :text
      add :primary_contact_phone, :text
      add :primary_contact_email, :text
    end
  end

  def down do
    alter table(:organizations) do
      remove :primary_contact_email
      remove :primary_contact_phone
      remove :primary_contact_name
    end

    drop constraint(:schools, "schools_chartering_agency_id_fkey")

    alter table(:schools) do
      remove :chartering_agency_id
    end
  end
end
