defmodule Emisint.Repo.Migrations.AddMdeImportLog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mde_import_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :import_type, :text, null: false
      add :original_filename, :text, null: false
      add :file_size_bytes, :bigint
      add :s3_key, :text
      add :status, :text, null: false, default: "uploading"
      add :records_processed, :bigint
      add :error_count, :bigint
      add :error_message, :text
      add :school_year, :text
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :uploaded_by_id,
          references(:users,
            column: :id,
            name: "mde_import_logs_uploaded_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:mde_import_logs, [:uploaded_by_id])

    create index(:mde_import_logs, [:status, :inserted_at])

    create index(:mde_import_logs, [:import_type, :inserted_at])
  end

  def down do
    drop constraint(:mde_import_logs, "mde_import_logs_uploaded_by_id_fkey")

    drop_if_exists index(:mde_import_logs, [:import_type, :inserted_at])

    drop_if_exists index(:mde_import_logs, [:status, :inserted_at])

    drop_if_exists index(:mde_import_logs, [:uploaded_by_id])

    drop table(:mde_import_logs)
  end
end
