defmodule Emisint.Repo.Migrations.AddAnalyticsDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:performance_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :snapshot_type, :text, null: false
      add :subject, :text, null: false
      add :grade_level, :text, null: false, default: "all"
      add :subgroup, :text, null: false, default: "all"
      add :testing_window, :text, null: false
      add :proficiency_rate, :decimal
      add :average_sgp, :decimal
      add :median_sgp, :decimal
      add :student_count, :bigint, null: false, default: 0
      add :organization_id, :uuid, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :school_id,
          references(:schools,
            column: :id,
            name: "performance_snapshots_school_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :academic_year_id,
          references(:academic_years,
            column: :id,
            name: "performance_snapshots_academic_year_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(
             :performance_snapshots,
             [
               :organization_id,
               :school_id,
               :academic_year_id,
               :snapshot_type,
               :subject,
               :grade_level,
               :subgroup,
               :testing_window
             ],
             name: "performance_snapshots_unique_school_year_snapshot_index"
           )

    create table(:intervention_triggers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :trigger_type, :text, null: false
      add :severity, :text, null: false, default: "medium"

      add :triggered_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :notes, :text
      add :resolved_at, :utc_datetime_usec
      add :organization_id, :uuid, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :school_id,
          references(:schools,
            column: :id,
            name: "intervention_triggers_school_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :academic_year_id,
          references(:academic_years,
            column: :id,
            name: "intervention_triggers_academic_year_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :schedule71_goal_id,
          references(:schedule71_goals,
            column: :id,
            name: "intervention_triggers_schedule71_goal_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :status, :text, null: false, default: "active"
    end

    create table(:data_sync_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :job_type, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :records_processed, :bigint
      add :records_failed, :bigint
      add :error_message, :text
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :metadata, :map, default: %{}
      add :organization_id, :uuid, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:data_sync_logs)

    drop constraint(:intervention_triggers, "intervention_triggers_school_id_fkey")

    drop constraint(:intervention_triggers, "intervention_triggers_academic_year_id_fkey")

    drop constraint(:intervention_triggers, "intervention_triggers_schedule71_goal_id_fkey")

    drop table(:intervention_triggers)

    drop_if_exists unique_index(
                     :performance_snapshots,
                     [
                       :organization_id,
                       :school_id,
                       :academic_year_id,
                       :snapshot_type,
                       :subject,
                       :grade_level,
                       :subgroup,
                       :testing_window
                     ],
                     name: "performance_snapshots_unique_school_year_snapshot_index"
                   )

    drop constraint(:performance_snapshots, "performance_snapshots_school_id_fkey")

    drop constraint(:performance_snapshots, "performance_snapshots_academic_year_id_fkey")

    drop table(:performance_snapshots)
  end
end
