defmodule Emisint.Repo.Migrations.AddRegistryDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:students, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :uic, :text, null: false
      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :date_of_birth, :date
      add :gender, :text
      add :active, :boolean, default: true
      add :economically_disadvantaged, :boolean, default: false
      add :english_learner, :boolean, default: false
      add :special_education, :boolean, default: false
      add :organization_id, :uuid, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:students, [:organization_id, :uic],
             name: "students_unique_uic_per_org_index"
           )

    create table(:enrollments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :grade_level, :text, null: false
      add :status, :text, null: false, default: "active"
      add :enrolled_at, :date, null: false
      add :exited_at, :date
      add :organization_id, :uuid, null: false
      add :school_id, :uuid, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :student_id,
          references(:students,
            column: :id,
            name: "enrollments_student_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :academic_year_id, :uuid, null: false
    end

    create table(:academic_years, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:enrollments) do
      modify :academic_year_id,
             references(:academic_years,
               column: :id,
               name: "enrollments_academic_year_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(
             :enrollments,
             [:organization_id, :student_id, :academic_year_id, :school_id],
             name: "enrollments_unique_enrollment_index"
           )

    alter table(:academic_years) do
      add :label, :text, null: false
      add :start_date, :date, null: false
      add :end_date, :date, null: false
      add :fall_window_start, :date
      add :fall_window_end, :date
      add :winter_window_start, :date
      add :winter_window_end, :date
      add :spring_window_start, :date
      add :spring_window_end, :date
      add :active, :boolean, default: true
      add :organization_id, :uuid, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:academic_years, [:organization_id, :label],
             name: "academic_years_unique_label_per_org_index"
           )
  end

  def down do
    drop_if_exists unique_index(:academic_years, [:organization_id, :label],
                     name: "academic_years_unique_label_per_org_index"
                   )

    alter table(:academic_years) do
      remove :updated_at
      remove :created_at
      remove :organization_id
      remove :active
      remove :spring_window_end
      remove :spring_window_start
      remove :winter_window_end
      remove :winter_window_start
      remove :fall_window_end
      remove :fall_window_start
      remove :end_date
      remove :start_date
      remove :label
    end

    drop_if_exists unique_index(
                     :enrollments,
                     [:organization_id, :student_id, :academic_year_id, :school_id],
                     name: "enrollments_unique_enrollment_index"
                   )

    drop constraint(:enrollments, "enrollments_academic_year_id_fkey")

    alter table(:enrollments) do
      modify :academic_year_id, :uuid
    end

    drop table(:academic_years)

    drop constraint(:enrollments, "enrollments_student_id_fkey")

    drop table(:enrollments)

    drop_if_exists unique_index(:students, [:organization_id, :uic],
                     name: "students_unique_uic_per_org_index"
                   )

    drop table(:students)
  end
end
