defmodule Emisint.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mde_sss_schools, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :lookup_key, :text, null: false
      add :school_code, :text
      add :school_name, :text, null: false
      add :needs_review, :boolean, null: false, default: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:mde_sss_schools, [:school_code])

    create unique_index(:mde_sss_schools, [:lookup_key],
             name: "mde_sss_schools_unique_lookup_key_index"
           )

    create table(:mde_sss_comparison_groups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :comparison_code, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :anchor_school_id,
          references(:mde_sss_schools,
            column: :id,
            name: "mde_sss_comparison_groups_anchor_school_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:mde_sss_comparison_groups, [:anchor_school_id])

    create unique_index(:mde_sss_comparison_groups, [:comparison_code],
             name: "mde_sss_comparison_groups_unique_comparison_code_index"
           )

    create table(:mde_sss_comparison_group_members, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :comparison_group_id,
          references(:mde_sss_comparison_groups,
            column: :id,
            name: "mde_sss_comparison_group_members_comparison_group_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :school_id,
          references(:mde_sss_schools,
            column: :id,
            name: "mde_sss_comparison_group_members_school_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:mde_sss_comparison_group_members, [:school_id])

    create index(:mde_sss_comparison_group_members, [:comparison_group_id])

    create unique_index(:mde_sss_comparison_group_members, [:comparison_group_id, :school_id],
             name: "mde_sss_comparison_group_members_unique_group_member_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :mde_sss_comparison_group_members,
                     [:comparison_group_id, :school_id],
                     name: "mde_sss_comparison_group_members_unique_group_member_index"
                   )

    drop constraint(
           :mde_sss_comparison_group_members,
           "mde_sss_comparison_group_members_comparison_group_id_fkey"
         )

    drop constraint(
           :mde_sss_comparison_group_members,
           "mde_sss_comparison_group_members_school_id_fkey"
         )

    drop_if_exists index(:mde_sss_comparison_group_members, [:comparison_group_id])

    drop_if_exists index(:mde_sss_comparison_group_members, [:school_id])

    drop table(:mde_sss_comparison_group_members)

    drop_if_exists unique_index(:mde_sss_comparison_groups, [:comparison_code],
                     name: "mde_sss_comparison_groups_unique_comparison_code_index"
                   )

    drop constraint(:mde_sss_comparison_groups, "mde_sss_comparison_groups_anchor_school_id_fkey")

    drop_if_exists index(:mde_sss_comparison_groups, [:anchor_school_id])

    drop table(:mde_sss_comparison_groups)

    drop_if_exists unique_index(:mde_sss_schools, [:lookup_key],
                     name: "mde_sss_schools_unique_lookup_key_index"
                   )

    drop_if_exists index(:mde_sss_schools, [:school_code])

    drop table(:mde_sss_schools)
  end
end
