defmodule Emisint.Repo.Migrations.AddSchoolResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :school_id, :uuid
    end

    create table(:schools, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:users) do
      modify :school_id,
             references(:schools,
               column: :id,
               name: "users_school_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:schools) do
      add :name, :text, null: false
      add :mde_district_code, :text, null: false
      add :mde_building_code, :text, null: false
      add :city, :text
      add :county, :text
      add :active, :boolean, default: true
      add :organization_id, :uuid, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:schools, [:organization_id, :mde_building_code],
             name: "schools_unique_building_code_per_org_index"
           )

    alter table(:enrollments) do
      modify :school_id,
             references(:schools,
               column: :id,
               name: "enrollments_school_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:enrollments, [:organization_id, :school_id])
  end

  def down do
    drop_if_exists index(:enrollments, [:organization_id, :school_id])

    drop constraint(:enrollments, "enrollments_school_id_fkey")

    alter table(:enrollments) do
      modify :school_id, :uuid
    end

    drop_if_exists unique_index(:schools, [:organization_id, :mde_building_code],
                     name: "schools_unique_building_code_per_org_index"
                   )

    alter table(:schools) do
      remove :updated_at
      remove :created_at
      remove :organization_id
      remove :active
      remove :county
      remove :city
      remove :mde_building_code
      remove :mde_district_code
      remove :name
    end

    drop constraint(:users, "users_school_id_fkey")

    alter table(:users) do
      modify :school_id, :uuid
    end

    drop table(:schools)

    alter table(:users) do
      remove :school_id
    end
  end
end
