defmodule Emisint.Repo.Migrations.AddPerformanceIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create_if_not_exists index(:schedule71_goals, [:organization_id, :school_id])

    create_if_not_exists index(:performance_snapshots, [:organization_id, :school_id, :snapshot_type])

    create_if_not_exists index(:performance_snapshots, [:organization_id, :school_id, :academic_year_id])

    create_if_not_exists index(:mde_state_assessment_results, [:rollup_level, :school_year, :subject])

    create_if_not_exists index(:mde_state_assessment_results, [:mde_district_id, :school_year])

    create_if_not_exists index(:mde_state_assessment_results, [:mde_building_id, :school_year])

    create_if_not_exists index(:intervention_triggers, [:organization_id, :school_id, :trigger_type, :status])

    create_if_not_exists index(:intervention_triggers, [
             :organization_id,
             :school_id,
             :academic_year_id,
             :status
           ])

    create_if_not_exists index(:intervention_triggers, [:organization_id, :status])

    create_if_not_exists index(:enrollments, [:organization_id, :student_id, :academic_year_id])

    create_if_not_exists index(:enrollments, [:organization_id, :school_id, :academic_year_id])

    create_if_not_exists index(:enrollments, [:organization_id, :school_id])

    create_if_not_exists index(:data_sync_logs, [:organization_id, :created_at])

    create_if_not_exists index(:data_sync_logs, [:organization_id, :job_type])

    create_if_not_exists index(:charter_contracts, [:organization_id, :status])

    create_if_not_exists index(:charter_contracts, [:organization_id, :school_id])

    create_if_not_exists index(:assessment_results, [
             :organization_id,
             :student_id,
             :academic_year_id,
             :subject,
             :testing_window
           ])

    create_if_not_exists index(:assessment_results, [:organization_id, :student_id, :academic_year_id])

    create_if_not_exists index(:assessment_results, [:organization_id, :academic_year_id])
  end

  def down do
    drop_if_exists index(:assessment_results, [:organization_id, :academic_year_id])

    drop_if_exists index(:assessment_results, [:organization_id, :student_id, :academic_year_id])

    drop_if_exists index(:assessment_results, [
                     :organization_id,
                     :student_id,
                     :academic_year_id,
                     :subject,
                     :testing_window
                   ])

    drop_if_exists index(:charter_contracts, [:organization_id, :school_id])

    drop_if_exists index(:charter_contracts, [:organization_id, :status])

    drop_if_exists index(:data_sync_logs, [:organization_id, :job_type])

    drop_if_exists index(:data_sync_logs, [:organization_id, :created_at])

    drop_if_exists index(:enrollments, [:organization_id, :school_id])

    drop_if_exists index(:enrollments, [:organization_id, :school_id, :academic_year_id])

    drop_if_exists index(:enrollments, [:organization_id, :student_id, :academic_year_id])

    drop_if_exists index(:intervention_triggers, [:organization_id, :status])

    drop_if_exists index(:intervention_triggers, [
                     :organization_id,
                     :school_id,
                     :academic_year_id,
                     :status
                   ])

    drop_if_exists index(:intervention_triggers, [
                     :organization_id,
                     :school_id,
                     :trigger_type,
                     :status
                   ])

    drop_if_exists index(:mde_state_assessment_results, [:mde_building_id, :school_year])

    drop_if_exists index(:mde_state_assessment_results, [:mde_district_id, :school_year])

    drop_if_exists index(:mde_state_assessment_results, [:rollup_level, :school_year, :subject])

    drop_if_exists index(:performance_snapshots, [:organization_id, :school_id, :academic_year_id])

    drop_if_exists index(:performance_snapshots, [:organization_id, :school_id, :snapshot_type])

    drop_if_exists index(:schedule71_goals, [:organization_id, :school_id])
  end
end
