defmodule Emisint.Repo.Migrations.CleanupRemovedResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :school_id
    end

    # Drop tables for removed resources (order respects FK dependencies)
    drop_if_exists table(:goal_evaluations_versions)
    drop_if_exists table(:goal_evaluations)
    drop_if_exists table(:intervention_triggers)
    drop_if_exists table(:schedule71_goals_versions)
    drop_if_exists table(:schedule71_goals)
    drop_if_exists table(:charter_contracts_versions)
    drop_if_exists table(:charter_contracts)
    drop_if_exists table(:performance_snapshots)
    drop_if_exists table(:assessment_results)
    drop_if_exists table(:enrollments)
    drop_if_exists table(:students)
    drop_if_exists table(:academic_years)
    drop_if_exists table(:benchmark_providers)
    drop_if_exists table(:data_sync_logs)
    drop_if_exists table(:schools)
  end

  def down do
    alter table(:users) do
      add :school_id, :uuid
    end
  end
end
