defmodule Emisint.Repo.Migrations.MdeRollupSupport do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:mde_state_assessment_results) do
      modify :mde_building_id, :uuid, null: true
      add :rollup_level, :text, null: false, default: "building"

      add :mde_district_id,
          references(:mde_districts,
            column: :id,
            name: "mde_state_assessment_results_mde_district_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :mde_isd_id,
          references(:mde_isds,
            column: :id,
            name: "mde_state_assessment_results_mde_isd_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(
             :mde_state_assessment_results,
             [
               :mde_district_id,
               :rollup_level,
               :school_year,
               :test_type,
               :test_population,
               :grade_content_tested,
               :subject,
               :report_category
             ],
             name: "mde_state_assessment_results_unique_district_rollup_index"
           )

    create unique_index(
             :mde_state_assessment_results,
             [
               :mde_isd_id,
               :rollup_level,
               :school_year,
               :test_type,
               :test_population,
               :grade_content_tested,
               :subject,
               :report_category
             ],
             name: "mde_state_assessment_results_unique_isd_rollup_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :mde_state_assessment_results,
                     [
                       :mde_isd_id,
                       :rollup_level,
                       :school_year,
                       :test_type,
                       :test_population,
                       :grade_content_tested,
                       :subject,
                       :report_category
                     ],
                     name: "mde_state_assessment_results_unique_isd_rollup_index"
                   )

    drop_if_exists unique_index(
                     :mde_state_assessment_results,
                     [
                       :mde_district_id,
                       :rollup_level,
                       :school_year,
                       :test_type,
                       :test_population,
                       :grade_content_tested,
                       :subject,
                       :report_category
                     ],
                     name: "mde_state_assessment_results_unique_district_rollup_index"
                   )

    drop constraint(
           :mde_state_assessment_results,
           "mde_state_assessment_results_mde_district_id_fkey"
         )

    drop constraint(:mde_state_assessment_results, "mde_state_assessment_results_mde_isd_id_fkey")

    alter table(:mde_state_assessment_results) do
      remove :mde_isd_id
      remove :mde_district_id
      remove :rollup_level
      modify :mde_building_id, :uuid, null: false
    end
  end
end
