defmodule Emisint.Repo.Migrations.AddSgpDistrictRollup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:mde_sgp_results) do
      modify :mde_building_id, :uuid, null: true
      add :rollup_level, :text, null: false, default: "building"

      add :mde_district_id,
          references(:mde_districts,
            column: :id,
            name: "mde_sgp_results_mde_district_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:mde_sgp_results, [:rollup_level, :school_year, :subject])

    create index(:mde_sgp_results, [:mde_district_id, :school_year])

    create unique_index(
             :mde_sgp_results,
             [:mde_district_id, :rollup_level, :school_year, :grade, :subject, :testing_group],
             name: "mde_sgp_results_unique_district_grade_subject_group_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :mde_sgp_results,
                     [
                       :mde_district_id,
                       :rollup_level,
                       :school_year,
                       :grade,
                       :subject,
                       :testing_group
                     ],
                     name: "mde_sgp_results_unique_district_grade_subject_group_index"
                   )

    drop constraint(:mde_sgp_results, "mde_sgp_results_mde_district_id_fkey")

    drop_if_exists index(:mde_sgp_results, [:mde_district_id, :school_year])

    drop_if_exists index(:mde_sgp_results, [:rollup_level, :school_year, :subject])

    alter table(:mde_sgp_results) do
      remove :mde_district_id
      remove :rollup_level
      modify :mde_building_id, :uuid, null: false
    end
  end
end
