defmodule Emisint.Repo.Migrations.AddEmoSchoolOverride do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:emo_school_overrides, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :management_organization, :text, null: false
      add :entity_code, :text, null: false
      add :action, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:emo_school_overrides, [:management_organization, :entity_code],
             name: "emo_school_overrides_unique_override_index"
           )
  end

  def down do
    drop_if_exists unique_index(:emo_school_overrides, [:management_organization, :entity_code],
                     name: "emo_school_overrides_unique_override_index"
                   )

    drop table(:emo_school_overrides)
  end
end
