defmodule Emisint.Repo.Migrations.EmoContactImport do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mde_emo_contacts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :district_code, :text, null: false
      add :psa_official_name, :text
      add :chartering_agency, :text
      add :management_organization, :text
      add :contact_name, :text
      add :contact_phone, :text
      add :contact_email, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:mde_emo_contacts, [:district_code],
             name: "mde_emo_contacts_unique_district_code_index"
           )
  end

  def down do
    drop_if_exists unique_index(:mde_emo_contacts, [:district_code],
                     name: "mde_emo_contacts_unique_district_code_index"
                   )

    drop table(:mde_emo_contacts)
  end
end
