defmodule Emisint.Repo.Migrations.CreateCrd do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mde_composite_resident_districts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :school_year, :text, null: false
      add :charter_district_code, :text, null: false
      add :charter_entity_name, :text
      add :crd_district_code, :text, null: false
      add :resident_entity_name, :text
      add :grade, :text
      add :nonresident_students_enrolled, :bigint

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :mde_district_id,
          references(:mde_districts,
            column: :id,
            name: "mde_composite_resident_districts_mde_district_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:mde_composite_resident_districts, [:mde_district_id])

    create index(:mde_composite_resident_districts, [:charter_district_code])

    create unique_index(
             :mde_composite_resident_districts,
             [:school_year, :charter_district_code, :crd_district_code],
             name: "mde_composite_resident_districts_unique_crd_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :mde_composite_resident_districts,
                     [:school_year, :charter_district_code, :crd_district_code],
                     name: "mde_composite_resident_districts_unique_crd_index"
                   )

    drop constraint(
           :mde_composite_resident_districts,
           "mde_composite_resident_districts_mde_district_id_fkey"
         )

    drop_if_exists index(:mde_composite_resident_districts, [:charter_district_code])

    drop_if_exists index(:mde_composite_resident_districts, [:mde_district_id])

    drop table(:mde_composite_resident_districts)
  end
end
