defmodule Emisint.Repo.Migrations.AddApiKeyAuth do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create_if_not_exists table(:messages, primary_key: false) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :text, :text, null: false
      add :tool_calls, {:array, :map}
      add :tool_results, {:array, :map}
      add :source, :text, null: false, default: "user"
      add :complete, :boolean, null: false, default: true
      add :conversation_id, :uuid, null: false
      add :response_to_id, :uuid
    end

    create_if_not_exists table(:conversations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    execute("""
    DO $$ BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'messages_conversation_id_fkey'
      ) THEN
        ALTER TABLE messages
          ADD CONSTRAINT messages_conversation_id_fkey
          FOREIGN KEY (conversation_id) REFERENCES conversations(id);
      END IF;
    END $$;
    """)

    execute("""
    DO $$ BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'messages_response_to_id_fkey'
      ) THEN
        ALTER TABLE messages
          ADD CONSTRAINT messages_response_to_id_fkey
          FOREIGN KEY (response_to_id) REFERENCES messages(id);
      END IF;
    END $$;
    """)

    alter table(:conversations) do
      add_if_not_exists :title, :text

      add_if_not_exists :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add_if_not_exists :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    execute("ALTER TABLE conversations ADD COLUMN IF NOT EXISTS user_id uuid")

    execute("""
    DO $$ BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'conversations_user_id_fkey'
      ) THEN
        ALTER TABLE conversations
          ADD CONSTRAINT conversations_user_id_fkey
          FOREIGN KEY (user_id) REFERENCES users(id);
      END IF;
    END $$;
    """)
  end

  def down do
    drop constraint(:conversations, "conversations_user_id_fkey")

    alter table(:conversations) do
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :title
    end

    drop constraint(:messages, "messages_conversation_id_fkey")

    drop constraint(:messages, "messages_response_to_id_fkey")

    alter table(:messages) do
      modify :response_to_id, :uuid
      modify :conversation_id, :uuid
    end

    drop table(:conversations)

    drop table(:messages)
  end
end
