// Emisint — Comprehensive School Report
// Data is injected by Imprintor as the global `elixir_data`

// ── Colour palette ───────────────────────────────────────────────────────────
#let c-green    = rgb("#16a34a")
#let c-green-bg = rgb("#f0fdf4")
#let c-amber    = rgb("#d97706")
#let c-amber-bg = rgb("#fffbeb")
#let c-red      = rgb("#dc2626")
#let c-red-bg   = rgb("#fef2f2")
#let c-gray     = rgb("#6b7280")
#let c-gray-bg  = rgb("#f9fafb")
#let c-border   = rgb("#e5e7eb")
#let c-heading  = rgb("#111827")
#let c-primary  = rgb("#2563eb")

// ── Page layout ──────────────────────────────────────────────────────────────
#set page(
  paper: "us-letter",
  margin: (top: 1.2in, bottom: 1in, left: 1in, right: 1in),
  header: context {
    if counter(page).get().first() > 1 [
      #set text(size: 8pt, fill: c-gray)
      #grid(
        columns: (1fr, 1fr),
        align: (left, right),
        [*#elixir_data.school.name* — Academic Performance Report],
        [Page #counter(page).display()]
      )
      #line(length: 100%, stroke: 0.5pt + c-border)
    ]
  },
  footer: context {
    set text(size: 8pt, fill: c-gray)
    line(length: 100%, stroke: 0.5pt + c-border)
    v(4pt)
    grid(
      columns: (1fr, 1fr),
      align: (left, right),
      [Confidential — Generated by Emisint APM],
      [Report Date: #elixir_data.school.report_date]
    )
  }
)

#set text(font: "Libertinus Serif", size: 10pt, fill: c-heading)
#set par(leading: 0.65em)

// ── Helpers ──────────────────────────────────────────────────────────────────

#let section-title(t) = {
  v(18pt)
  block(
    width: 100%,
    fill: c-primary,
    inset: (x: 10pt, y: 7pt),
    radius: 2pt,
    text(fill: white, weight: "bold", size: 11pt, t)
  )
  v(8pt)
}

#let status-badge(s) = {
  let (bg, fg, label) = if s == "exceeds" {
    (c-green-bg, c-green, "Exceeds")
  } else if s == "meets" {
    (c-green-bg, c-green, "Meets")
  } else if s == "approaching" {
    (c-amber-bg, c-amber, "Approaching")
  } else if s == "below" {
    (c-red-bg, c-red, "Below")
  } else if s == "insufficient_data" {
    (c-gray-bg, c-gray, "Insufficient Data")
  } else {
    (c-gray-bg, c-gray, "No Data")
  }
  box(
    fill: bg,
    inset: (x: 7pt, y: 3pt),
    radius: 10pt,
    text(fill: fg, weight: "bold", size: 8pt, label)
  )
}

#let severity-badge(s) = {
  let (bg, fg) = if s == "high" {
    (c-red-bg, c-red)
  } else if s == "medium" {
    (c-amber-bg, c-amber)
  } else {
    (c-gray-bg, c-gray)
  }
  box(
    fill: bg,
    inset: (x: 7pt, y: 3pt),
    radius: 10pt,
    text(fill: fg, weight: "bold", size: 8pt, upper(s))
  )
}

#let proficiency-color(rate) = {
  if rate >= 0.6 { c-green }
  else if rate >= 0.4 { c-amber }
  else { c-red }
}

#let proficiency-fill(rate) = {
  if rate >= 0.6 { c-green-bg }
  else if rate >= 0.4 { c-amber-bg }
  else { c-red-bg }
}

#let sgp-color(sgp) = {
  if sgp >= 50 { c-green }
  else if sgp >= 40 { c-amber }
  else { c-red }
}

#let fmt-pct(rate) = {
  str(calc.round(rate * 100, digits: 1)) + "%"
}

#let th(t) = table.cell(fill: rgb("#f3f4f6"), text(weight: "bold", size: 8.5pt, fill: c-gray, upper(t)))

#let capitalize(s) = {
  if s.len() == 0 { s }
  else { upper(s.first()) + s.slice(1) }
}

// ── Cover / Header ────────────────────────────────────────────────────────────
#block(
  width: 100%,
  fill: c-primary,
  inset: (x: 24pt, y: 20pt),
  radius: 4pt,
  {
    text(fill: white, size: 20pt, weight: "bold", elixir_data.school.name)
    v(6pt)
    text(fill: rgb("#bfdbfe"), size: 11pt, elixir_data.school.city)
    if elixir_data.school.mde_building_code != "" [
      #text(fill: rgb("#bfdbfe"), size: 11pt, " · MDE " + elixir_data.school.mde_building_code)
    ]
    v(10pt)
    grid(
      columns: (auto, auto, auto),
      gutter: 20pt,
      {
        text(fill: rgb("#93c5fd"), size: 8pt, "ACADEMIC YEAR")
        linebreak()
        text(fill: white, size: 10pt, weight: "semibold", elixir_data.academic_year)
      },
      if elixir_data.contract.authorizer != "" {
        stack(
          text(fill: rgb("#93c5fd"), size: 8pt, "AUTHORIZER"),
          linebreak(),
          text(fill: white, size: 10pt, weight: "semibold", elixir_data.contract.authorizer)
        )
      },
      if elixir_data.contract.status != "" {
        stack(
          text(fill: rgb("#93c5fd"), size: 8pt, "CONTRACT STATUS"),
          linebreak(),
          text(fill: white, size: 10pt, weight: "semibold", upper(elixir_data.contract.status))
        )
      }
    )
  }
)

#if elixir_data.contract.start_date != "" or elixir_data.contract.end_date != "" [
  #v(4pt)
  #text(size: 9pt, fill: c-gray)[
    Charter Contract: #elixir_data.contract.start_date — #elixir_data.contract.end_date
  ]
]

// ── Section 1: Proficiency ───────────────────────────────────────────────────
#section-title("Section 1 — State Assessment Proficiency")

#if elixir_data.proficiency.len() == 0 [
  #block(
    width: 100%,
    fill: c-gray-bg,
    inset: 16pt,
    radius: 3pt,
    text(fill: c-gray, style: "italic", "No proficiency data available for this school.")
  )
] else [
  #let subjects = elixir_data.proficiency.map(s => s.subject).dedup()

  #for subject in subjects [
    #let rows = elixir_data.proficiency.filter(s => s.subject == subject)

    #v(10pt)
    #text(weight: "bold", size: 10pt, upper(subject))
    #v(5pt)
    #table(
      columns: (2fr, 1fr, 2fr),
      stroke: 0.5pt + c-border,
      inset: (x: 10pt, y: 7pt),
      th("Testing Window"), th("Proficiency"), th("Rate"),
      ..for row in rows {(
        text(size: 9pt, capitalize(row.testing_window)),
        box(
          fill: proficiency-fill(row.proficiency_rate),
          inset: (x: 7pt, y: 3pt),
          radius: 3pt,
          text(fill: proficiency-color(row.proficiency_rate), weight: "bold", size: 9pt, fmt-pct(row.proficiency_rate))
        ),
        {
          let bar_pct = calc.min(row.proficiency_rate, 1.0)
          grid(
            columns: (bar_pct * 100% + 0.01%, 1fr),
            rows: 10pt,
            box(fill: proficiency-color(row.proficiency_rate), width: 100%, height: 100%, radius: (left: 3pt, right: if bar_pct >= 0.99 { 3pt } else { 0pt })),
            box(fill: rgb("#e5e7eb"), width: 100%, height: 100%, radius: (right: 3pt))
          )
        }
      )}
    )
    #v(4pt)
    #text(size: 8pt, fill: c-gray)[
      #rows.len() #if rows.len() == 1 { "window" } else { "windows" } ·
      Total students: #rows.fold(0, (acc, r) => acc + r.student_count)
    ]
  ]
]

// ── Section 2: Growth (SGP) ──────────────────────────────────────────────────
#section-title("Section 2 — Student Growth Percentiles (SGP)")

#if elixir_data.growth.len() == 0 [
  #block(
    width: 100%,
    fill: c-gray-bg,
    inset: 16pt,
    radius: 3pt,
    text(fill: c-gray, style: "italic", "No SGP data available for this school.")
  )
] else [
  #table(
    columns: (auto, 1.2fr, 1.5fr, 1fr, 1fr, 0.7fr),
    stroke: 0.5pt + c-border,
    inset: (x: 10pt, y: 7pt),
    th("Grade"), th("Subject"), th("Window"), th("Median SGP"), th("Avg SGP"), th("Students"),
    ..for row in elixir_data.growth {(
      text(size: 9pt, weight: "semibold", row.grade_level),
      text(size: 9pt, capitalize(row.subject)),
      text(size: 9pt, capitalize(row.testing_window)),
      text(
        fill: sgp-color(row.median_sgp),
        weight: "bold",
        size: 9pt,
        str(calc.round(row.median_sgp, digits: 1))
      ),
      text(
        fill: sgp-color(row.average_sgp),
        size: 9pt,
        str(calc.round(row.average_sgp, digits: 1))
      ),
      text(size: 9pt, fill: c-gray, str(row.student_count))
    )}
  )
  #v(4pt)
  #text(size: 8pt, fill: c-gray)[
    SGP Color: #box(fill: c-green-bg, inset: (x:5pt,y:2pt), radius:3pt, text(fill:c-green,size:7.5pt,"≥50 Strong"))
    #h(6pt)
    #box(fill: c-amber-bg, inset: (x:5pt,y:2pt), radius:3pt, text(fill:c-amber,size:7.5pt,"40–49 Typical"))
    #h(6pt)
    #box(fill: c-red-bg, inset: (x:5pt,y:2pt), radius:3pt, text(fill:c-red,size:7.5pt,"<40 Below"))
  ]
]

// ── Section 3: Schedule 7-1 Compliance ───────────────────────────────────────
#section-title("Section 3 — Schedule 7-1 Contractual Compliance")

#if elixir_data.goals.len() == 0 [
  #block(
    width: 100%,
    fill: c-gray-bg,
    inset: 16pt,
    radius: 3pt,
    text(fill: c-gray, style: "italic", "No Schedule 7-1 goals configured for this school.")
  )
] else [
  #table(
    columns: (2fr, 1fr, 1fr, 0.9fr, 0.9fr, 1fr),
    stroke: 0.5pt + c-border,
    inset: (x: 9pt, y: 7pt),
    th("Goal"), th("Type"), th("Subject"), th("Target"), th("Actual"), th("Status"),
    ..for g in elixir_data.goals {(
      text(size: 9pt, g.title),
      text(size: 9pt, fill: c-gray, capitalize(g.goal_type)),
      text(size: 9pt, fill: c-gray, capitalize(g.subject)),
      text(size: 9pt, if g.target_value != 0.0 { str(calc.round(g.target_value, digits: 1)) } else { "—" }),
      text(size: 9pt, if g.actual_value != 0.0 { str(calc.round(g.actual_value, digits: 1)) } else { "—" }),
      status-badge(g.status)
    )}
  )
  #v(4pt)
  #text(size: 8pt, fill: c-gray)[
    Status Key:
    #box(fill:c-green-bg, inset:(x:5pt,y:2pt), radius:3pt, text(fill:c-green,size:7.5pt,"Exceeds"))
    #h(4pt)
    #box(fill:c-green-bg, inset:(x:5pt,y:2pt), radius:3pt, text(fill:c-green,size:7.5pt,"Meets"))
    #h(4pt)
    #box(fill:c-amber-bg, inset:(x:5pt,y:2pt), radius:3pt, text(fill:c-amber,size:7.5pt,"Approaching"))
    #h(4pt)
    #box(fill:c-red-bg, inset:(x:5pt,y:2pt), radius:3pt, text(fill:c-red,size:7.5pt,"Below"))
  ]
]

// ── Section 4: Interventions ──────────────────────────────────────────────────
#section-title("Section 4 — Active Intervention Triggers")

#if elixir_data.active_triggers.len() == 0 [
  #block(
    width: 100%,
    fill: c-green-bg,
    inset: 16pt,
    radius: 3pt,
    {
      text(fill: c-green, weight: "bold", "✓  No active interventions")
      linebreak()
      text(fill: c-green, size: 9pt, "This school has no active intervention triggers at this time.")
    }
  )
] else [
  #table(
    columns: (1fr, 1.5fr, 1.2fr, auto),
    stroke: 0.5pt + c-border,
    inset: (x: 9pt, y: 7pt),
    th("Severity"), th("Type"), th("Date"), th("Notes"),
    ..for t in elixir_data.active_triggers {(
      severity-badge(t.severity),
      text(size: 9pt, capitalize(t.trigger_type)),
      text(size: 9pt, fill: c-gray, t.triggered_at),
      text(size: 9pt, fill: c-gray, if t.notes != "" { t.notes } else { "—" })
    )}
  )
]

// ── Signature / attestation block ────────────────────────────────────────────
#v(1fr)
#line(length: 100%, stroke: 0.5pt + c-border)
#v(4pt)
#grid(
  columns: (1fr, 1fr),
  gutter: 30pt,
  {
    text(size: 9pt, fill: c-gray, "Reviewed by: _______________________________")
    v(4pt)
    text(size: 8pt, fill: c-gray, "EMO Academic Officer")
  },
  {
    text(size: 9pt, fill: c-gray, "Date: _______________________________")
    v(4pt)
    text(size: 8pt, fill: c-gray, "Signature")
  }
)
